# configuration:
# https://docs.conduktor.io/platform/configuration/introduction
# https://docs.conduktor.io/platform/configuration/env-variables

organization:
  name: "${ORGANISATION_NAME}"
  
clusters:
  - id: default
    name: Local test kafka cluster
    color: "#0013E7"
    ignoreUntrustedCertificate: false
    bootstrapServers: "$KAFKA_BOOTSTRAP_SERVER"
    properties:
    labels: {}

auth:
  demo-users:
    - email: "${ADMIN_EMAIL}"
      password: "${ADMIN_PSW}"
      groups:
        - ADMIN